socialmedia/posts/urls.py
from django.urls import path 
from .views import post_comment_create_and_list_view , like_unlike_post

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
]

socialmedia/profiles/urls.py
from django.urls import path
from .views import  my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('myprofile/', my_profile_view, name='my_profile_view')
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view,name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

socialmedia/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')


    def _str_(self):
        return self.content
    
    def num_likes(self):
        return self.liked.all().count()
    
    def num_comments(self):
        return self.liked.all().count()

    class Meta:
        ordering = ('-created', )

class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return str(self.pk)


LIKE_CHOICES = {
    ('Like', 'Like'),
    ('unlike', 'Unlike'),
}
 
class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=10)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return self.user

socialmedia/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django import template
from django.template.defaultfilters import slugify

# Create your models here.

class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No Bio..", max_length=500)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User,blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()
    
    def get_all_authors_posts(self):
        return self.posts.all()
    
    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked +=1
        return total_liked

    def get_likes_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def _str_(self):
        return f"{self.first_name}-{self.created}"

    def save(self,*args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def _str_(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

socialmedia/profiles/forms.py
from django import forms
from .models import Profile

class ProfileModeForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ('first_name', 'last_name', 'bio','avatar')

socialmedia/posts/views.py
from django.shortcuts import render, redirect 
from .models import Post , Like
from profiles.models import Profile
# Create your views here.

def post_comment_create_and_list_view(request):
    qs = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    context = {
        'qs': qs,
        'profile': profile,

    }

    return render(request, 'posts/main.html', context)

def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST['post_id']
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'

            post_obj.save()
            like.save()
    return redirect('posts:main-post-view')

socialmedia/profiles/views.py
from django.shortcuts import render
from .models import Profile
from .forms import ProfileModeForm
# Create your views here.

def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModeForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'profiles/myprofile.html', context)

socialmedia/socialmedia/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home_view(request):
    user = request.user
    hello = 'Hello world'

    contaxt = {
        'user': user,
        'hello': hello,
    }
    return render(request,'social/home.html', contaxt)

socialmedia/posts/templates/posts/main.html
{% extends 'social/base.html' %}

{% block title %}
posts
{% endblock title %}

{% block content %}
<div class="ui grid">
   <div class="row">
     <div class="eleven wide column">
        {% for obj in qs %}
          <div class="ui fluid card">
             <div class="content">
               {{obj.content}}
            </div>
            <div class="content">
               <form action="{% url 'posts:like-post-view' %}" method="POST">
                   {% csrf_token %}
                   <input type="hidden" name="post_id" vlaue="{{obj.id}}">
                   <button  type="submit" class="ui red button">
                       {% if profile not in obj.liked.all %}
                         <i class="heart icon"></i>&nbsp;like
                       {% else %}
                          <i class="heart icon"></i>&nbsp;Unlike
                       {% endif %}
                   </button>
                    <a class="ui basic red left pointing label">
                      {{obj.num_likes}}
                    </a>
               </form>
            </div>
      </div>
      {% endfor %}
      </div>
      <div class="five wide column">
      From 
      {{profile}}
      </div>
   </row>
</div>
{% endblock content %}

socialmedia/profiles/templates/profiles/myprofile.html
{% extends 'social/base.html' %}

{% block title%}
My Profiles
{% endblock title %}

{% block content %}
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update Your Profile 
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url }}">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional info about you </div>
      <from action="" method="POST" class="ui form" enctype="multipart/form-data">
      {% csrf_token %}
      {{forn.as_p}}
      </div>
      </div>
      <div class="actions">
        <button type="submit" class="ui positive right labeled icon button">
        Update
        <i class="checkmark icon"></i>
        </button>
        </form>
        </div>
        </div>
    
    <div class="ui segment">
      {% if confirm %}
      <div class="ui green message">Your Profile Updated </div> 
      {% endif %}
      <h3>my profile: {{request.first_name}}</h3>
      <div class="ui grid">
        <div class="row">
          <div class="six wide colume">
             <img class="ui medium rounded image" src={{profile.avatar.url}}
             <div class="row mt-5">
                <button class='ui secondary button' id='model-btn'>Update your Profile</button>
              </div>
              <div class="ten wide column">
                 <table class="ui table">
                   <tbody>
                     <tr>
                        <td>username</td>
                        <td>{{profile.user}}</td>
                      </tr>
                      <tr>
                        <td>first name</td>
                        <td>{{profile.first_name}}</td>
                      </tr>
                      <tr>
                        <td>last name</td>
                        <td>{{profile.last_name}}
                      </tr>
                      <tr>
                         <td>bio</td>
                         <td>{{profile.bio}}</td>
                      </tr>
                      <tr>
                         <td>number of friends</td>
                         <td>{{profile.get_frirnds_no}}</td>
                      </tr>
                      <tr>
                        <td>number of friends</td>
                        <td>
                          <ul>
                            {% for friend in profile.get_friends %}
                                <li>{{friend}}</li>
                            {% endfor %}
                          </ul>
                        <td>
                      </tr>
                      <tr>
                        <td>Number of Posts</td>
                        <td>{{profile.get_posts_no}}</td>
                      </tr>
                      <tr>
                        <td>Number of Likes You have</td>
                        <td>{{profile.get_likes_given_no}}</td>
                      </tr>
                      <tr>
                        <td>Number of Likes Received</td>
                        <td>{{profile.get_likes_recieved_no}}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
{% endblock content %}

socialmedia/templates/social/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" type='text/css' href={% static  'style.css' %}
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>Social-Media - {% block title %}{% endblock title %}</title>
  </head>
  <body>
  {% include 'social/navbar.html' %}
    <div class="ui container">
      {% block content %}
      
      {% endblock content %}
    </div>

{% block scripts %}
{% endblock scripts %}
   
   <script type='text/javascript' src={% static '/main.js' %}></script>

  </body>
</html>

socialmedia/templates/social/home.html
{% extends 'social/base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
{{hello}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

socialmedia/templates/social/navbar.html
<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="" class="item">
        <h3>Social-Media</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="" class="item">
        Home
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="" class="item">
                        All Profiles
                    </a>
                    <a href="" class="item">
                        Send Invites
                    </a>
                    <a href="" class="item">
                        Received Invites
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="" class="item">
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>